spring.application.name=GINS

server.port=10000

spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class.name=com.mysql.cj.jdbc.Driver

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=500ms
spring.data.redis.connect-timeout=500ms

server.address=0.0.0.0

springdoc.swagger-ui.path=/docs

# Brevo (Sendinblue) REST API Configuration (Uses HTTPS port 443, avoiding blocked SMTP ports on Render)
brevo.api.key=${BREVO_API_KEY:}
brevo.sender.email=${BREVO_SENDER_EMAIL:}
brevo.sender.name=${BREVO_SENDER_NAME:} 

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.enabled=true

# This makes Spring Security send its logs to the Logback system
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

