spring.application.name=GINS

server.port=10000
#spring.jpa.defer-datasource-initialization=true
#spring.jpa.show-sql=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# \connect username@port

server.address=0.0.0.0

#spring.security.user.name=tapu
#spring.security.user.password=1234

springdoc.swagger-ui.path=/docs
