spring.application.name=GINS

server.port=10000
#spring. jpa.defer-datasource-initialization=true
#spring. jpa.show-sq1=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class.name=com.mysql.cj.jdbc.Driver

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=500ms
spring.data.redis.connect-timeout=500ms


# \connect username@port

server.address=0.0.0.0

#spring. security.user.name=tapu
#spring. security. user.password=1234

springdoc.swagger-ui.path=/docs

# Spring Mail Auto-Configuration (Externalized SMTP)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${SMTP_USERNAME:f4c9278dc54249}
spring.mail.password=${SMTP_PASSWORD:e9b3b0cd6eaab0}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true 